# Generated by Django 5.1 on 2025-10-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_and_projects', '0016_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_mode',
            field=models.CharField(choices=[('draft', 'Draft'), ('moderation', 'Moderation'), ('published', 'Published'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='draft', max_length=15, verbose_name='Task mode'),
        ),
    ]
