# Generated by Django 5.1 on 2025-10-19 16:16

import uuid
from django.db import migrations, models


def generate_uuids_and_slugs(apps, schema_editor):
    """Generate UUIDs and slugs for existing Task records"""
    Task = apps.get_model('services_and_projects', 'Task')
    for task in Task.objects.all():
        # Generate new UUID for each task
        task.uuid = uuid.uuid4()
        # Generate slug based on UUID
        task.slug = f"t-{task.uuid.hex[:8]}"
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('services_and_projects', '0031_alter_typeofview_name'),
    ]

    operations = [
        # Step 1: Add UUID field without default, nullable
        migrations.AddField(
            model_name='task',
            name='uuid',
            field=models.UUIDField(editable=False, null=True, blank=True),
        ),
        # Step 2: Add slug field, nullable
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        # Step 3: Generate UUIDs and slugs for all existing records
        migrations.RunPython(generate_uuids_and_slugs, migrations.RunPython.noop),
        # Step 4: Make uuid field non-nullable with default and unique
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        # Step 5: Make slug field unique
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
