

services:
  web:
    build: .
    container_name: offerland-web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DB: offerland_django_db
      POSTGRES_USER: offerland_user
      POSTGRES_PASSWORD: offerland_django123
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:17.2
    container_name: postgres_db2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U offerland_user -d offerland_django_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: offerland_django_db
      POSTGRES_USER: offerland_user
      POSTGRES_PASSWORD: offerland_django123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        BUILD_CMD: build
    container_name: offerland-frontend
    volumes:
      - ./frontend:/app-frontend
      - /app-frontend/node_modules
    ports:
      - "5173:5173"
      - "3000:3000"
      - "8080:8080"
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    container_name: offerland-mcp-server
    ports:
      - "3025:3025"
    environment:
      - NODE_ENV=development
    command: ["npx", "@agentdeskai/browser-tools-mcp@latest"]

volumes:
  postgres_data:


